namespace: argocd
repoURL: https://github.com/Lamlmao/Helm.git
project: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
apps:    

  - name: argocd-apps
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    source:
      targetRevision: main
      path: charts/argocd-app
      valueFiles:
        - ../../env/dev/argocd-apps/values.yaml