apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  labels:
    app: dotnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: lamnh43rg.azurecr.io/dotnetapp
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-svc
  labels:
    app: dotnetapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dotnetapp
