apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnetapp-ingress
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "dotnetapp"
    appgw.ingress.kubernetes.io/ssl-redirect: "true" 
    appgw.ingress.kubernetes.io/health-probe-path: "/WeatherForecast"
spec:
  ingressClassName: "azure-application-gateway"
  # tls:
  #   - hosts:
  #       - dotnetapp.azure.hugotech.online
  #     secretName: <guestbook-secret-name>
  rules:
    - host: dotnetapp.azure.hugotech.online
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: dotnetapp-svc
                port:
                  name: http
#kubectl create secret tls dotnetapp-secret-tls --key /etc/letsencrypt/live/dotnetapp.azure.hugotech.online/privkey.pem --cert /etc/letsencrypt/live/dotnetapp.azure.hugotech.online/fullchain.pem
